export const actionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_ALL_ITEM_IN_CART: 'DELETE_ALL_ITEM_IN_CART',
    DELETE_ONE_ITEM_IN_CART: 'DELETE_ONE_ITEM_IN_CART',
    REFRESH_CART: 'REFRESH_CART'
}; 